name: Auto Deploy to Shared Host ğŸš€

on:
  workflow_call:

jobs:
  checkout:
    name: ğŸ‰ To the moon ğŸŒ•
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup NodeJS Dependencies ğŸ“¦
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          run: |
            npm install
            npm run build

      - name: Sync files ğŸ”„
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          args: --delete
          exclude: .git*
          state-name: ${{ github.event.pull_request.number }}
          log-level: verbose
